services:
  ros2:
    build:
      context: ./docker_setup
      dockerfile: Dockerfile
    image: ros2:latest
    container_name: ros2
    tty: true
    stdin_open: true
    command: bash
    ports:
      - "8000:5000"
      - "5901:5901"
    volumes:
      - ./workspace:/workspace
      - /opt/nvidia/vpi3:/opt/nvidia/vpi3
      - /usr/lib/aarch64-linux-gnu:/usr/lib/aarch64-linux-gnu
    devices:
      - /dev/bus/usb:/dev/bus/usb
    privileged: true
    environment:
      - vpi_DIR=/opt/nvidia/vpi3/lib/aarch64-linux-gnu/cmake/vpi
