#!/bin/bash
# Run with sudo to install udev rules for OCTANE cameras.
# Plug each camera in one at a time, run the discovery step, then re-run this
# script to regenerate the full rules file.

RULES_FILE=/etc/udev/rules.d/99-octane-cameras.rules

cat > "$RULES_FILE" << 'EOF'
# OCTANE camera udev rules — generated by setup_cameras.sh
# Maps physical USB ports to stable /dev/cam_* symlinks.
# Rebuild by running setup_cameras.sh whenever cameras are reassigned.

# ── Orbbec Astra Pro ──────────────────────────────────────────────────────────
# RGB UVC interface → /dev/cam_orbbec (video capture device only, not metadata)
SUBSYSTEM=="video4linux", ENV{ID_PATH}=="platform-3610000.usb-usb-0:4.2.4.1:1.0", ATTR{index}=="0", SYMLINK+="cam_orbbec", MODE="0666"
# Depth/IR sensor — grant non-root access for OpenNI2 / ros2_astra_camera driver
SUBSYSTEM=="usb", ATTR{idVendor}=="2bc5", ATTR{idProduct}=="0403", MODE="0666", GROUP="video"
SUBSYSTEM=="usb", ATTR{idVendor}=="2bc5", ATTR{idProduct}=="0501", MODE="0666", GROUP="video"

# ── Innomaker U20CAM 1080p (5×) ───────────────────────────────────────────────
# Positions assigned by USB port — cables must stay in assigned ports.
# Add entries here as each camera is plugged in and assigned a position.
SUBSYSTEM=="video4linux", ENV{ID_PATH}=="platform-3610000.usb-usb-0:4.2.3:1.0",  ATTR{index}=="0", SYMLINK+="cam_left_front",  MODE="0666"
SUBSYSTEM=="video4linux", ENV{ID_PATH}=="platform-3610000.usb-usb-0:4.2.2:1.0",  ATTR{index}=="0", SYMLINK+="cam_left_side",   MODE="0666"
SUBSYSTEM=="video4linux", ENV{ID_PATH}=="platform-3610000.usb-usb-0:4.1.3:1.0",  ATTR{index}=="0", SYMLINK+="cam_right_front", MODE="0666"
SUBSYSTEM=="video4linux", ENV{ID_PATH}=="platform-3610000.usb-usb-0:4.1.2:1.0",  ATTR{index}=="0", SYMLINK+="cam_right_side",  MODE="0666"
SUBSYSTEM=="video4linux", ENV{ID_PATH}=="platform-3610000.usb-usb-0:4.1.1:1.0",  ATTR{index}=="0", SYMLINK+="cam_back_rear",   MODE="0666"
# SUBSYSTEM=="video4linux", ENV{ID_PATH}=="platform-3610000.usb-usb-0:PORT:1.0", ATTR{index}=="0", SYMLINK+="cam_POSITION", MODE="0666"

EOF

udevadm control --reload-rules
udevadm trigger --subsystem-match=video4linux
udevadm trigger --subsystem-match=usb

echo "[OK] Rules written to $RULES_FILE and reloaded."
echo "     Expected symlinks: cam_orbbec, cam_left_front, cam_left_side, cam_right_front, cam_right_side, cam_back_rear"
ls -la /dev/cam_* 2>/dev/null || echo "     (no /dev/cam_* yet — replug camera to trigger)"
