drive:
  ramp_time_up:   0.33  # seconds to ramp from 0 to 100% throttle
  ramp_time_down: 0.33  # seconds to ramp from 100% to 0 throttle
  dead_band:      0.02  # min speed change before re-sending a command
